
export const allProduct = [
  {
    name: "Plano Mid-Century Modern Tufted 3-Seater Sofa, Light Gray/Dark Brown, Light Gray",
    price:" 5543.00",
    series: "3640 Kinetic",
    description: "Sofa in kensington feather w/chrome leg",
    designedBy: "Michael wolk",
    sku: "364020C",
    images: ["lazar_product_list/Kinetic Sofa/364020C_thumb.jpeg", "lazar_product_list/Kinetic Sofa/364020C_2.jpeg"],
    category: "sofa",
    Options:["Wood_Finish","Metal_Swivel_Base_Options","Memory_Foam"],
    dimensions: "31H  X 95W X 45D",
    height:"31",
    width:"95",
    depth:"45",
  },
  {
    name: "Manhattan Sofa",
    price:"5147.00",
    series: "",
    description:
      "Sofa In BELLISIMO WHITE, 22x22 Knife Edge Toss Pillows In Taos Piano (Not Standard)",
    dimensions: "105W  X 31H X 36D ",
    designedBy: "Stanley Jay Friedman",
    sku: "144120C",
    images: ["lazar_product_list/Manhattan Sofa/144120C_thumb.jpeg", "lazar_product_list/Manhattan Sofa/144120C_1.jpeg"],
    category: "sofa",
    Options:["Metal_Swivel_Base_Options","Memory_Foam"],
    height:"31",
    width:"105",
    depth:"36",
  },
  {
    name: "Kinetic Condo Sofa",
    price:"5047.00" ,
    series: "5047.00",
    description: "CHESAPEAKE OUTDOOR SWELL",
    dimensions: "84W X 32D X 18H",
    designedBy: "Michael Wolk",
    sku: "OD364051",
    images: ["lazar_product_list/Kinetic Condo Sofa/OD364051_thumb.jpeg", "lazar_product_list/Kinetic Condo Sofa/OD364051_1.jpeg"],
    category: "sofa",
    options:["Wood_Finish","Metal_Swivel_Base_Options","Memory_Foam"],
    height:"18",
    width:"84",
    depth:"32",
  },
  {
    name: "Grove Swivel Chair",
    price:"3024.00" ,
    series: "2818 GROVE SERIES",
    description:
      "Swivel Chair In Bellisimo Grey W/25 Stainless Steel Swivel Base",
    dimensions: "31W X 33H X 33D",
    designedBy: "Michael Wolk",
    sku: "2818SW",
    images: ["lazar_product_list/Grove Swivel/2818SW_thumb.jpeg", "lazar_product_list/Grove Swivel/2818SW_1.jpeg"],
    category: "Swivel",
    Options:[],
    height:"",
    width:"",
    depth:"",
  },
  {
    name: "Grove Chaise",
    price:"2819.00" ,
    series: "2818 GROVE SERIES",
    description:
      "Swivel Chair In Bellisimo Grey W/25 Stainless Steel Swivel Base",
    dimensions: `33" X H33"W X 57.5"D`,
    designedBy: "Michael Wolk",
    sku: "281807R",
    images: ["lazar_product_list/Grove Chaise/281807R_thumb.png", "lazar_product_list/Grove Chaise/281807R_1.png", "lazar_product_list/Grove Chaise/281807R_2.png"],
    category: "chaise",
    Options:[],
    height:"31",
    width:"33",
    depth:"57.5",
  },
  {
    name: "Amaro Swivel Chair",
    price:"2123.00" ,
    series: "17804 AMARO",
    description: "360 Swivel, W/Tight Seat & Channel Detail",
    dimensions: "33W X 32H X 33D",
    designedBy: "",
    sku: "17804SW",
    images: ["lazar_product_list/Amaro Swivel Chair/17804SW_thumb.jpeg", "lazar_product_list/Amaro Swivel Chair/17804SW_1.jpeg"],
    category: "swivel",
    Options:[],
    height:"33",
    width:"32",
    depth:"33",
  },
  {
    name: "Easy Rider Swivel",
    price:"2565.00" ,
    series: "",
    description: "IN HAVEN OYSTER",
    dimensions: `30"W X 30H X 32.5"D`,
    designedBy: "Rick Lee",
    sku: "701204",
    images: ["lazar_product_list/Easy Rider Swivel Chair/701204_thumb.png", "lazar_product_list/Easy Rider Swivel Chair/701204_1.png", "lazar_product_list/Easy Rider Swivel Chair/701204_2.png"],
    category: "swivel",
    height:"30",
    width:"30",
    depth:"32.5",
  },
  {
    name: "Selene Swivel",
    price:"5743.00" ,
    series: "",
    description: "IN HAVEN OYSTER",
    dimensions: "36HX56.5Wx56.5D",
    designedBy: "Rick Lee",
    sku: "156086",
    images: ["lazar_product_list/Selene Swivel/156086SW_thumb.jpeg", "lazar_product_list/Selene Swivel/156086SW_2.jpeg"],
    category: "swivel",
    height:"36",
    width:"56.6",
    depth:"56.5",
  },
  {
    name: "BELIZE SOFA - PLATINUM COLLECTION",
    price:"5047.00" ,
    series: "",
    description: "Platinum Collection",
    dimensions:
      "94W X 34.5H X 39.5D",
    designedBy: " JOHN MASCHERONI",
    sku: "7034",
    images: ["lazar_product_list/Belize Sofa/507220_thumb.jpeg", "lazar_product_list/Belize Sofa/507220_1.jpeg"],
    catogory: "sofa",
    options:["Wood_Finish"],
    height:"94",
    width:"34.5",
    depth:"39.5",
  },
  {
    name: "Manhattan Occasional Chair Petite",
    price:"3134.00" ,
    series: "",
    description: "IN MOLLY PEWTER",
    dimensions: "40W X 30.5H X 34D",
    designedBy: " Stanley Jay Friedman",
    sku: "144104XC",
    images: ["lazar_product_list/Manhattan Chair (x)/144104XC_thumb.png", "lazar_product_list/Manhattan Chair (x)/144104XC_1.png", "lazar_product_list/Manhattan Chair (x)/144104XC_2.png"],
    category: "chair",
    height:"20.5",
    width:"40",
    depth:"34",
  },
  {
    name: "Gina Curved Sofa - Platinum Collection",
    price:"6248.00" ,
    series: "",
    description:
      "Curved Sofa In Britain Ivory W/Espresso Finish (Toss Pillows Not Standard) 22x22 Knife Edge Pillows In Prospect Platinum",
    dimensions: "92W X 28H X 39D",
    designedBy: "John Mascheroni",
    sku: "145543",
    images: ["lazar_product_list/Gina Curved Sofa - Platinum Collection/145543_thumb.jpeg", "lazar_product_list/Gina Curved Sofa - Platinum Collection/145543_2.jpeg"],
    category: "sofa",
    height:"28",
    width:"92",
    depth:"39",
  },
  {
    name: "BELIZE ARMLESS SWIVEL CHAIR - PLATINUM COLLECTION",
    price:"2819.00" ,
    series: "",
    description: "Moxie White",
    dimensions:
      "33.5H X 38W X 39D, Seat Height 18.5, Seat Width 38, Seat Depth 21",
    designedBy: "JOHN MASCHERONI",
    sku: "703402SW BELIZE",
    images: ["lazar_product_list/Kinetic Swivel Chair/364004SWC_thumb.jpeg"],
    category: "swivel",
    height:"33.5",
    width:"38",
    depth:"39",
  },
  {
    name: "Jeremiah 4pc Sectional",
    price:"5988.00" ,
    series: "JEREMIAH 1416",
    description:
      "1 Arm Chaise (LAF), Armless Sofa, Corner, 1 Arm Sofa (RAF) In Alleghany Platinum With Espresso Finish",
    dimensions:
      "38W X 29H X 68D",
    designedBy: "",
    sku: "1416",
    images: ["lazar_product_list/Jeremiah 4pc Sectional/1416_thumb.jpeg"],
    options: "sofa",
    height:"29",
    width:"38",
    depth:"68",
  },
  {
    name: "Kinetic Swivel Chair",
    price:"2767.00" ,
    series: "",
    description: "Swivel Chair In Bellisimo White ",
    designedBy: "Michael Wolk",
    sku: "364004SWC",
    images: ["lazar_product_list/Kinetic Swivel Chair/364004SWC_thumb.jpeg", "lazar_product_list/Kinetic Swivel Chair/364004SWC.jpeg"],
    category: "swivel",
    dimensions: "23W X 33H X 28D",
    height:"33",
    width:"23",
    depth:"28",
  },
]
export const selectedItems = [
  
]